### ISSUE TITLE
Tenant > Creation error returns wrong HTTP code

### ISSUE THREAD

**Issue by Ninjeneer** [sap-labs-france/ev-server#2288]
![image.png](https://images.zenhubusercontent.com/5dfd46a3563ec65759521f2d/ca1d5b70-5929-427a-b203-81ea94c62442)

**Comment by Ninjeneer** [comment]
Fixed during issue creation :)

**Comment by jerome-benoit** [comment]
There is still an issue: tenant with empty subdomain are allowed and it makes one unit test fails. It must not be allowed.

**Comment by Ninjeneer** [comment]
Ok, I can handle it.

Just one thing : 
Currently tenant creation return a `HTTPError.USER_EMAIL_ALREADY_EXIST_ERROR` if name or subdomain are already used. It needs to be obviously changed, but is there a preferred custom HTTP code I should use, or can I choose any unused 5XX code ?

**Comment by LucasBrazi06** [comment]
FYI, I already fixed the empty sub-domain in the Json schema, sent you a comment already this afternoon.

**Comment by LucasBrazi06** [comment]
> Currently tenant creation returns a `HTTPError.USER_EMAIL_ALREADY_EXIST_ERROR` if name or subdomain are already used. It needs to be obviously changed, but is there a preferred custom HTTP code I should use, or can I choose any unused 5XX code ?

For the time being choose one available not yet used.
We will one day change this and always return an application error code in the response.

**Comment by jerome-benoit** [comment]
I guess that issue is solved but a proper return code will be chosen, right?

**Comment by LucasBrazi06** [comment]
> I guess that issue is solved but a proper return code will be chosen, right?

Yes

**Comment by LucasBrazi06** [comment]
@Ninjeneer I just tested and it seems that a generic message is displayed despite the right error code is returned:

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/4120a29a-a320-4fd9-9667-d3f1a92b9be4)

Could you check?

**Comment by Ninjeneer** [comment]
Indeed, added specific errors for name/subdomains.
